name: Build and Deploy Sphinx Documentation

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  push:
    branches:
      - main
      - progress

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Host OS

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Pull and Run Docker Container with Rocky Linux 8
      run: |
        docker pull rockylinux/rockylinux:8
        docker run -d --name rockylinux -v $(pwd):/github/workspace rockylinux/rockylinux:8 sleep infinity || docker start rockylinux

    - name: Install Development Tools, Python, and Dependencies
      run: |
        docker exec rockylinux dnf groupinstall -y "Development Tools"
        docker exec rockylinux dnf install -y python3 python3-pip
        docker exec rockylinux python3 -m venv /venv
        docker exec rockylinux /venv/bin/pip install --upgrade pip
        docker exec rockylinux /venv/bin/pip install -r /github/workspace/requirements.txt

    - name: Install Sphinx
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        # Add any other Sphinx-related installation commands here

    - name: Build Sphinx Documentation
      run: |
        docker exec rockylinux bash -c "source /venv/bin/activate && cd /github/workspace/docs && make html"

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'  # Ensures deployment happens only from the main branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: /github/workspace/docs/build/html
        keep_files: true  # Set to false if you want a clean deployment on GitHub Pages
