name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - main
      - progress

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]  # macOS and Ubuntu as a stand-in for Rocky Linux

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Adjust the Python version as needed

    - name: Install Sphinx
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        # Add any other Sphinx-related installation commands here

    - name: Build Sphinx Documentation
      run: |
        cd docs
        make html

    - name: Deploy to GitHub Pages
      if: matrix.os == 'ubuntu-latest'  # Deploy only from the Ubuntu job
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
        keep_files: true  # Set to false to clean the publishing directory
